services:
  dashboard:
    image: marcusfrancisco/dashboard-produtividade:latest
    container_name: app-dashboard-produtividade
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./google_credentials.json:/app/google_credentials.json:ro
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs