name: Auto Versioning e Tagging

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump da Versão, Arquivo e Tag
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: 'VERSION'
          output-file: 'CHANGELOG.md'