name: Auto Versioning e Tagging

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump da Versão, Arquivo e Tag
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: 'VERSION.json'
          output-file: 'CHANGELOG.md'
      
      - name: 🐳 Login no Docker Hub
        # Só roda se o passo acima criou uma versão nova
        if: steps.changelog.outputs.skipped == 'false' 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extrair metadados para o Docker
        if: steps.changelog.outputs.skipped == 'false'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: marcusfrancisco/dashboard-produtividade
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.changelog.outputs.tag }}

      - name: Build e Push da Imagem
        if: steps.changelog.outputs.skipped == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}